// emf::artop::codegen —— ArtopCppGenerator 实现
// 对齐 Java: org.artop.aal.gautosar.codegen + autosar448.codegen
//
// 在 CppGenerator 基类生成标准 EMF C++ 代码的基础上，追加 ARTOP 特有步骤：
//   1. generateResourceAndFactory: 生成 <Pkg>ResourceImpl / <Pkg>ResourceFactoryImpl
//      （继承 AutosarXMLResource / AutosarXMLResourceFactory）
//   2. generateRootExtensions: 在根 EClass 注入 mixed/extensions 字段
//      （对齐 Java ExtendedMetaData，输出 ARTOP_ROOT_EXTENSIONS.md 记录）
#include "emf/artop/codegen/ArtopCppGenerator.h"
#include "emf/ecore/codegen/StringUtils.h"
#include "emf/ecore/EcoreImpls.h"

#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

namespace emf::artop::codegen {

namespace {

// 包名 → 类名前缀（library → Library, autosar40 → Autosar40）
std::string pkgClassPrefix(const std::string& pkgName) {
    return emf::ecore::codegen::capitalizeFirst(pkgName);
}

// 子目录名（= 包名）
std::string subdir(const std::string& pkgName) {
    return pkgName.empty() ? "unnamed" : pkgName;
}

}  // namespace

ArtopCppGenerator::ArtopCppGenerator(ArtopGenConfig config)
    : emf::ecore::codegen::CppGenerator(config.base),  // copy（不 move），保留 config 完整
      artopConfig_(std::move(config)) {}

// generateFromFile: 基类加载 ecore 并生成标准 EMF 文件，
// 然后对已加载的 package 追加 ARTOP 扩展。
// 注意：基类 generateFromFile() 内部调用 2-arg generateFromPackage（非 virtual），
// 所以 ARTOP 扩展不会通过 virtual 分发触发，需在此显式调用。
void ArtopCppGenerator::generateFromFile() {
    emf::ecore::codegen::CppGenerator::generateFromFile();
    // 基类已加载 package_，对它追加 ARTOP 扩展
    auto* pkg = package();
    if (pkg) {
        if (artopConfig_.generateResource) {
            generateResourceAndFactory(pkg);
        }
        if (artopConfig_.injectRootExtensions) {
            generateRootExtensions(pkg);
        }
    }
}

// generateFromPackage: 先调基类生成标准 EMF 文件，再追加 ARTOP 扩展
void ArtopCppGenerator::generateFromPackage(emf::ecore::EPackage* package) {
    // 1. 基类：生成 Package/Factory/Class/Switch/AdapterFactory/Validator
    emf::ecore::codegen::CppGenerator::generateFromPackage(package);

    if (!package) return;

    // 2. ARTOP 扩展
    if (artopConfig_.generateResource) {
        generateResourceAndFactory(package);
    }
    if (artopConfig_.injectRootExtensions) {
        generateRootExtensions(package);
    }
}

// 生成 <Pkg>ResourceImpl.h 和 <Pkg>ResourceFactoryImpl.h
// 对齐 Java: Autosar448ResourceImpl / Autosar448ResourceFactoryImpl
void ArtopCppGenerator::generateResourceAndFactory(emf::ecore::EPackage* package) {
    if (!package) return;
    std::string pkgName = package->getName();
    std::string prefix = pkgClassPrefix(pkgName);
    std::string dir = subdir(pkgName);
    std::string ns = artopConfig_.base.baseNamespace;

    // <Pkg>ResourceImpl.h
    {
        std::ostringstream w;
        w << "// <auto-generated/>\n";
        w << "#pragma once\n";
        w << "#include \"emf/artop/runtime/AutosarResource.h\"\n";
        w << "#include \"emf/artop/runtime/AutosarReleaseDescriptor.h\"\n";
        w << "\n";
        w << "namespace " << ns << " {\n";
        w << "\n";
        w << "// " << prefix << "ResourceImpl: AUTOSAR XML Resource 实现\n";
        w << "// 对齐 Java: " << prefix << "ResourceImpl extends AutosarXMLResourceImpl\n";
        w << "class " << prefix << "ResourceImpl : public emf::artop::runtime::AutosarXMLResource {\n";
        w << "public:\n";
        w << "    " << prefix << "ResourceImpl() = default;\n";
        w << "    explicit " << prefix << "ResourceImpl(emf::common::URI uri)\n";
        w << "        : AutosarXMLResource(std::move(uri)) {}\n";
        w << "    ~" << prefix << "ResourceImpl() override = default;\n";
        w << "};\n";
        w << "\n";
        w << "}  // namespace " << ns << "\n";
        writeFile(dir + "/" + prefix + "ResourceImpl.h", w.str());
    }

    // <Pkg>ResourceFactoryImpl.h
    {
        std::ostringstream w;
        w << "// <auto-generated/>\n";
        w << "#pragma once\n";
        w << "#include \"emf/artop/runtime/AutosarResourceFactory.h\"\n";
        w << "#include \"" << prefix << "ResourceImpl.h\"\n";
        w << "\n";
        w << "namespace " << ns << " {\n";
        w << "\n";
        w << "// " << prefix << "ResourceFactoryImpl: AUTOSAR Resource 工厂\n";
        w << "// 对齐 Java: " << prefix << "ResourceFactoryImpl extends AutosarXMLResourceFactoryImpl\n";
        w << "class " << prefix << "ResourceFactoryImpl\n";
        w << "    : public emf::artop::runtime::AutosarXMLResourceFactory {\n";
        w << "public:\n";
        w << "    using AutosarXMLResourceFactory::AutosarXMLResourceFactory;\n";
        w << "\n";
        w << "    std::unique_ptr<emf::common::Resource> createResource(\n";
        w << "        const emf::common::URI& uri) override {\n";
        w << "        auto res = std::make_unique<" << prefix << "ResourceImpl>(uri);\n";
        w << "        if (getAutosarRelease()) {\n";
        w << "            res->setAutosarRelease(getAutosarRelease());\n";
        w << "            res->setSchemaLocation(getAutosarRelease()->getSchemaLocation());\n";
        w << "        }\n";
        w << "        return res;\n";
        w << "    }\n";
        w << "};\n";
        w << "\n";
        w << "}  // namespace " << ns << "\n";
        writeFile(dir + "/" + prefix + "ResourceFactoryImpl.h", w.str());
    }
}

// 在根 EClass 注入 mixed/extensions 字段
// 对齐 Java: ExtendedMetaData + FeatureMapUtil
// 当前简化：输出 ARTOP_ROOT_EXTENSIONS.md 记录注入计划
void ArtopCppGenerator::generateRootExtensions(emf::ecore::EPackage* package) {
    if (!package) return;
    std::string pkgName = package->getName();
    std::string dir = subdir(pkgName);

    std::ostringstream w;
    w << "# ARTOP Root Extensions Injection Plan\n";
    w << "\n";
    w << "Package: " << pkgName << "\n";
    w << "Namespace: " << artopConfig_.baseNamespaceUri << "\n";
    w << "SchemaLocation: " << artopConfig_.schemaLocation << "\n";
    w << "\n";
    w << "## Root EClass candidates for mixed/extensions injection\n";
    w << "\n";

    int count = 0;
    for (auto* c : package->getEClassifiers()) {
        auto* cls = dynamic_cast<emf::ecore::EClass*>(c);
        if (!cls) continue;
        // 根 EClass 通常是包中不作为其他 EClass 的 EReference target 的类
        // 简化：列出所有非抽象 EClass
        if (!cls->isAbstract()) {
            w << "- " << cls->getName() << "\n";
            ++count;
        }
    }

    if (count == 0) {
        w << "(none)\n";
    }

    w << "\n";
    w << "## Injection details\n";
    w << "\n";
    w << "Each root EClass will receive:\n";
    w << "- `mixed` (EFeatureMap, many-valued) — captures unknown XML elements\n";
    w << "- `extensions` (EFeatureMap, many-valued) — captures XML comments/PIs\n";
    w << "\n";
    w << "Generated by ArtopCppGenerator\n";

    writeFile(dir + "/ARTOP_ROOT_EXTENSIONS.md", w.str());
}

void ArtopCppGenerator::writeFile(const std::string& relativePath,
                                   const std::string& content) const {
    std::filesystem::path p =
        std::filesystem::path(artopConfig_.base.outputDirectory) / relativePath;
    std::error_code ec;
    std::filesystem::create_directories(p.parent_path(), ec);
    std::ofstream f(p);
    if (f.is_open()) {
        f << content;
    }
}

}  // namespace emf::artop::codegen
