<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.eclipse.sphinx.releng</groupId>
	<artifactId>org.eclipse.sphinx.releng.builds</artifactId>
	<version>0.13.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<properties>
		<platform.version.name>2020-09</platform.version.name>
	</properties>
	<modules>
		<module>./parent</module>
		<module>../../tools/org.eclipse.sphinx.targets/${platform.version.name}</module>

		<!-- Plug-ins -->
		<module>../../plugins/org.eclipse.sphinx.emf.check.catalog.edit</module>
		<module>../../plugins/org.eclipse.sphinx.emf.check.catalog.editor</module>
		<module>../../plugins/org.eclipse.sphinx.emf.check.catalog</module>
		<module>../../plugins/org.eclipse.sphinx.emf.check.ui</module>
		<module>../../plugins/org.eclipse.sphinx.emf.check</module>
		<module>../../plugins/org.eclipse.sphinx.emf.compare.ui</module>
		<module>../../plugins/org.eclipse.sphinx.emf.compare</module>
		<module>../../plugins/org.eclipse.sphinx.emf.editors.forms.nebula</module>
		<module>../../plugins/org.eclipse.sphinx.emf.editors.forms</module>
		<module>../../plugins/org.eclipse.sphinx.emf.editors.viatra.query</module>
		<module>../../plugins/org.eclipse.sphinx.emf.editors</module>
		<module>../../plugins/org.eclipse.sphinx.emf.explorer</module>
		<module>../../plugins/org.eclipse.sphinx.emf.viatra.query</module>
		<module>../../plugins/org.eclipse.sphinx.emf.metamodelgen.ui</module>
		<module>../../plugins/org.eclipse.sphinx.emf.metamodelgen</module>
		<module>../../plugins/org.eclipse.sphinx.emf.mwe.dynamic.headless</module>
		<module>../../plugins/org.eclipse.sphinx.emf.mwe.dynamic.launching.ui</module>
		<module>../../plugins/org.eclipse.sphinx.emf.mwe.dynamic.launching</module>
		<module>../../plugins/org.eclipse.sphinx.emf.mwe.dynamic.ui</module>
		<module>../../plugins/org.eclipse.sphinx.emf.mwe.dynamic</module>
		<module>../../plugins/org.eclipse.sphinx.emf.mwe</module>
		<module>../../plugins/org.eclipse.sphinx.emf.search.ui.viatra.query</module>
		<module>../../plugins/org.eclipse.sphinx.emf.search.ui</module>
		<module>../../plugins/org.eclipse.sphinx.emf.serialization.generators</module>
		<module>../../plugins/org.eclipse.sphinx.emf.serialization</module>
		<module>../../plugins/org.eclipse.sphinx.emf.ui</module>
		<module>../../plugins/org.eclipse.sphinx.emf.validation.bridge</module>
		<module>../../plugins/org.eclipse.sphinx.emf.validation.ui</module>
		<module>../../plugins/org.eclipse.sphinx.emf.validation</module>
		<module>../../plugins/org.eclipse.sphinx.emf.workspace.viatra.query</module>
		<module>../../plugins/org.eclipse.sphinx.emf.workspace.ui</module>
		<module>../../plugins/org.eclipse.sphinx.emf.workspace</module>
		<module>../../plugins/org.eclipse.sphinx.emf</module>
		<module>../../plugins/org.eclipse.sphinx.gmf.runtime.ui</module>
		<module>../../plugins/org.eclipse.sphinx.gmf.workspace</module>
		<module>../../plugins/org.eclipse.sphinx.jdt</module>
		<module>../../plugins/org.eclipse.sphinx.pde</module>
		<module>../../plugins/org.eclipse.sphinx.platform.launching</module>
		<module>../../plugins/org.eclipse.sphinx.platform.ui</module>
		<module>../../plugins/org.eclipse.sphinx.platform</module>
		<module>../../plugins/org.eclipse.sphinx.xtend.typesystem.emf.ui</module>
		<module>../../plugins/org.eclipse.sphinx.xtend.typesystem.emf</module>
		<module>../../plugins/org.eclipse.sphinx.xtendxpand.ui</module>
		<module>../../plugins/org.eclipse.sphinx.xtendxpand</module>

		<!-- Examples -->
		<module>../../examples/org.eclipse.sphinx.examples.actions</module>
		<module>../../examples/org.eclipse.sphinx.examples.codegen.xpand.ui</module>
		<module>../../examples/org.eclipse.sphinx.examples.common.ui</module>
		<module>../../examples/org.eclipse.sphinx.examples.emf.compare.reports.csv</module>
		<module>../../examples/org.eclipse.sphinx.examples.emf.compare.reports.html</module>
		<module>../../examples/org.eclipse.sphinx.examples.explorer</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird.ide.ui</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird.ide</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird.metamodelgen.ui</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird.metamodelgen</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird10.edit</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird10.ide.ui</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird10.viatra.query</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird10</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.check</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.codegen.xpand</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.diagram.gmf</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.edit</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.editors.nebula</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.emf.compare</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.ide</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.ide.ui</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.viatra.query</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.splitting</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.transform.xtend</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.validation</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20.workflows</module>
		<module>../../examples/org.eclipse.sphinx.examples.hummingbird20</module>
		<module>../../examples/org.eclipse.sphinx.examples.tests.perf</module>
		<module>../../examples/org.eclipse.sphinx.examples.transform.xtend.ui</module>
		<module>../../examples/org.eclipse.sphinx.examples.uml2.ide.ui</module>
		<module>../../examples/org.eclipse.sphinx.examples.uml2.ide</module>
		<module>../../examples/org.eclipse.sphinx.examples.validation.ui</module>
		<module>../../examples/org.eclipse.sphinx.examples.views.documentation</module>
		<module>../../examples/org.eclipse.sphinx.examples.workflows.lib</module>
		<module>../../examples/org.eclipse.sphinx.examples.workflows</module>

		<!-- Tests -->
		<module>../../tests/org.eclipse.sphinx.tests.emf.check</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.editors.integration</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.viatra.query</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.integration</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.mwe.dynamic.integration</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.serialization.generators</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.serialization</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.ui.integration</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.workspace.integration</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.workspace.ui</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.workspace</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.workspace.extension</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.search.ui</module>
		<module>../../tests/org.eclipse.sphinx.tests.emf.validation</module>
		<module>../../tests/org.eclipse.sphinx.tests.jdt.integration</module>
		<module>../../tests/org.eclipse.sphinx.tests.jdt</module>
		<module>../../tests/org.eclipse.sphinx.tests.platform.integration</module>
		<module>../../tests/org.eclipse.sphinx.tests.platform</module>
		<module>../../tests/org.eclipse.sphinx.tests.xtendxpand.integration</module>
		<module>../../tests/org.eclipse.sphinx.testutils.integration.referenceworkspace.xtendxpand</module>
		<module>../../tests/org.eclipse.sphinx.testutils.integration.referenceworkspace</module>
		<module>../../tests/org.eclipse.sphinx.testutils.integration</module>
		<module>../../tests/org.eclipse.sphinx.testutils</module>

		<!-- Features -->
		<module>../../features/org.eclipse.sphinx.core-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.check-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.compare-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.editors-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.editors.forms-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.editors.forms.nebula-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.viatra.query-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.metamodelgen-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.mwe.dynamic-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.navigators-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.search-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.serialization-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.serialization.generators-feature</module>
		<module>../../features/org.eclipse.sphinx.emf.validation-feature</module>
		<module>../../features/org.eclipse.sphinx.gmf.editors-feature</module>
		<module>../../features/org.eclipse.sphinx.jdtpde-feature</module>
		<module>../../features/org.eclipse.sphinx.xtendxpand-feature</module>

		<module>../../features/org.eclipse.sphinx.examples.core-feature</module>
		<module>../../features/org.eclipse.sphinx.examples.emf.compare-feature</module>
		<module>../../features/org.eclipse.sphinx.examples.viatra.query-feature</module>
		<module>../../features/org.eclipse.sphinx.examples.metamodels.hummingbird-feature</module>
		<module>../../features/org.eclipse.sphinx.examples.metamodels.hummingbird.viatra.query-feature</module>
		<module>../../features/org.eclipse.sphinx.examples.metamodels.hummingbird.nebula-feature</module>
		<module>../../features/org.eclipse.sphinx.examples.metamodels.uml2-feature</module>
		<module>../../features/org.eclipse.sphinx.examples.navigators-feature</module>
		<module>../../features/org.eclipse.sphinx.examples.nebula-feature</module>
		<module>../../features/org.eclipse.sphinx.examples.validation-feature</module>
		<module>../../features/org.eclipse.sphinx.examples.workflows-feature</module>
		<module>../../features/org.eclipse.sphinx.examples.xtendxpand-feature</module>

		<module>../../features/org.eclipse.sphinx-feature</module>
		<module>../../features/org.eclipse.sphinx.doc-feature</module>
		<module>../../features/org.eclipse.sphinx.examples-feature</module>
		<module>../../features/org.eclipse.sphinx.viatra.query-feature</module>
		<module>../../features/org.eclipse.sphinx.viatra.query.sdk-feature</module>
		<module>../../features/org.eclipse.sphinx.nebula-feature</module>
		<module>../../features/org.eclipse.sphinx.nebula.sdk-feature</module>
		<module>../../features/org.eclipse.sphinx.sdk-feature</module>
		<module>../../features/org.eclipse.sphinx.testutils-feature</module>
		<module>../../features/org.eclipse.sphinx.thirdparty-feature</module>

		<!-- Documentation -->
		<module>../../docs/org.eclipse.sphinx.doc.isv</module>

		<module>./repository</module>
	</modules>
</project>
