<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<prerequisites>
		<maven>3.0</maven>
	</prerequisites>
	<groupId>org.eclipse.sphinx.releng</groupId>
	<artifactId>org.eclipse.sphinx.releng.parent</artifactId>
	<version>0.13.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<url>http://www.eclipse.org/sphinx</url>
	<description>Integrated modeling tool platform that eases the development of IDE-like tool support for modeling languages used in software and systems development</description>
	<licenses>
		<license>
			<name>Eclipse Public License v2.0</name>
			<comments>
       All rights reserved.

       This program and the accompanying materials are made
       available under the terms of the Eclipse Public License v2.0
       which accompanies this distribution, and is available at
       http://www.eclipse.org/legal/epl-v10.htm
			</comments>
		</license>
	</licenses>
	<organization>
		<name>Eclipse</name>
		<url>http://www.eclipse.org</url>
	</organization>
	<scm>
		<developerConnection>scm:git:git://git.eclipse.org/gitroot/sphinx/org.eclipse.sphinx.git</developerConnection>
	</scm>
	<issueManagement>
		<url>https://bugs.eclipse.org/bugs</url>
	</issueManagement>
	<ciManagement>
		<url>https://ci.eclipse.org/sphinx/</url>
		<system>Eclipse Jenkins</system>
	</ciManagement>
	<properties>
		<tycho.version>2.7.0</tycho.version>
		<xtend.maven.plugin.version>2.17.0</xtend.maven.plugin.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.build.resourceEncoding>UTF-8</project.build.resourceEncoding>
		<platform.version.name>2020-09</platform.version.name>
	</properties>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>2.6</version>
				<configuration>
					<encoding>ISO-8859-1</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<version>${tycho.version}</version>
				<extensions>true</extensions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<version>${tycho.version}</version>
				<configuration>
					<target>
						<artifact>
							<groupId>org.eclipse.sphinx.targets</groupId>
							<artifactId>${platform.version.name}</artifactId>
							<version>0.13.1-SNAPSHOT</version>
						</artifact>
					</target>
					<environments>
						<environment>
							<os>win32</os>
							<ws>win32</ws>
							<arch>x86_64</arch>
						</environment>
						<environment>
							<os>macosx</os>
							<ws>cocoa</ws>
							<arch>x86_64</arch>
						</environment>
						<environment>
							<os>linux</os>
							<ws>gtk</ws>
							<arch>x86_64</arch>
						</environment>
					</environments>
					<dependency-resolution>
						<extraRequirements>
							<requirement>
								<type>eclipse-plugin</type>
								<id>org.eclipse.osgi.compatibility.state</id>
								<versionRange>[1.0.200,2.0.0)</versionRange>
							</requirement>
						</extraRequirements>
					</dependency-resolution>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-source-plugin</artifactId>
				<version>${tycho.version}</version>
				<executions>
					<execution>
						<id>plugin-source</id>
						<goals>
							<goal>plugin-source</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho.extras</groupId>
				<artifactId>tycho-source-feature-plugin</artifactId>
				<version>${tycho.version}</version>
				<executions>
					<execution>
						<id>source-feature</id>
						<phase>package</phase>
						<goals>
							<goal>source-feature</goal>
						</goals>
						<configuration>
							<includeBinaryFeature>false</includeBinaryFeature>
							<!-- Non-breakable space, as normal spaces are trimmed. -->
							<labelSuffix>&nbsp;Source
							</labelSuffix>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-p2-plugin</artifactId>
				<version>${tycho.version}</version>
				<executions>
					<execution>
						<!-- Don't attach (default) metadata before the "generate-source-feature"
							execution. -->
						<id>default-p2-metadata-default</id>
						<configuration>
							<attachP2Metadata>false</attachP2Metadata>
						</configuration>
					</execution>
					<execution>
						<!-- Do attach metadata after the "generate-source-feature" execution. -->
						<id>attach-p2-metadata</id>
						<phase>package</phase>
						<goals>
							<goal>p2-metadata</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-surefire-plugin</artifactId>
				<version>${tycho.version}</version>
				<configuration>
					<includes>
						<include>**/*Test.java</include>
						<include>**/*Test2.java</include>
					</includes>
					<excludes>
						<!-- Test mojo matches TestProject be default and treats it as PojoTest -->
						<exclude>**/Test*.class</exclude>
					</excludes>
					<useUIHarness>false</useUIHarness>
					<argLine>${tycho.surefire.extra.vmargs}</argLine>

					<!-- Uncomment to remote debug tests run by Maven/Tycho build -->
					<!-- <argLine>${tycho.surefire.extra.vmargs} -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y</argLine> -->
				</configuration>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>os-macosx</id>
			<activation>
				<os>
					<family>mac</family>
				</os>
			</activation>
			<properties>
				<!-- !!! Important Note !!! The following element MUST be written in a single line. Otherwise the build will fail under Max OS X
				(see https://bugs.eclipse.org/bugs/show_bug.cgi?id=427693). In particular, be careful when auto formatting this file with Ctrl+Shift+F
				as it tends to break up this line into several pieces. -->
				<tycho.surefire.extra.vmargs>-Xmx512m -XstartOnFirstThread</tycho.surefire.extra.vmargs>
			</properties>
		</profile>
		<profile>
			<id>os-other</id>
			<activation>
				<os>
					<family>!mac</family>
				</os>
			</activation>
			<properties>
				<tycho.surefire.extra.vmargs>-Xmx512m</tycho.surefire.extra.vmargs>
			</properties>
		</profile>
		<profile>
			<id>eclipse-sign</id>
			<pluginRepositories>
				<pluginRepository>
					<id>eclipse-cbi</id>
					<url>https://repo.eclipse.org/content/repositories/cbi-releases</url>
				</pluginRepository>
			</pluginRepositories>
			<build>
				<plugins>
					<plugin>
						<groupId>org.eclipse.tycho</groupId>
						<artifactId>target-platform-configuration</artifactId>
						<version>${tycho.version}</version>
						<configuration>
							<includePackedArtifacts>true</includePackedArtifacts>
						</configuration>
					</plugin>
					<plugin>
						<groupId>org.eclipse.tycho.extras</groupId>
						<artifactId>tycho-pack200a-plugin</artifactId>
						<version>${tycho.version}</version>
						<executions>
							<execution>
								<id>pack200-normalize</id>
								<goals>
									<goal>normalize</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.eclipse.cbi.maven.plugins</groupId>
						<artifactId>eclipse-jarsigner-plugin</artifactId>
						<version>1.3.2</version>
						<executions>
							<execution>
								<id>sign</id>
								<goals>
									<goal>sign</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.eclipse.tycho.extras</groupId>
						<artifactId>tycho-pack200b-plugin</artifactId>
						<version>${tycho.version}</version>
						<executions>
							<execution>
								<id>pack200-pack</id>
								<goals>
									<goal>pack</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.eclipse.tycho</groupId>
						<artifactId>tycho-p2-plugin</artifactId>
						<version>${tycho.version}</version>
						<executions>
							<execution>
								<id>p2-metadata</id>
								<phase>package</phase>
								<goals>
									<goal>p2-metadata</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<defaultP2Metadata>false</defaultP2Metadata>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>