// AdapterFactoryEmitter.cpp —— 生成 <Pkg>AdapterFactory.h/.cpp
// 对齐 Java: <Pkg>AdapterFactory.java / <Pkg>AdapterFactoryImpl.java
#include "emf/ecore/codegen/AdapterFactoryEmitter.h"
#include "emf/ecore/codegen/StringUtils.h"
#include "emf/ecore/EcorePackage.h"
#include "emf/common/ENotifier.h"
#include <string>
#include <vector>

namespace emf::ecore::codegen {

namespace {
std::string nsPath(emf::ecore::EPackage* p, const std::string& base, const std::string& parentPath) {
    std::string fullName = parentPath.empty() ? p->getName()
                                              : (parentPath + "/" + p->getName());
    std::string r;
    r.reserve(fullName.size() * 2);
    for (char c : fullName) {
        if (c == '/') r += "::";
        else r += c;
    }
    if (base.empty()) return r;
    return base + "::" + r;
}
std::vector<emf::ecore::EClass*> collectClasses(emf::ecore::EPackage* p) {
    std::vector<emf::ecore::EClass*> out;
    for (auto* c : p->getEClassifiers()) {
        if (auto* cls = dynamic_cast<emf::ecore::EClass*>(c)) out.push_back(cls);
    }
    return out;
}
}  // namespace

AdapterFactoryEmitter::AdapterFactoryEmitter(emf::ecore::EPackage* package, const std::string& baseNamespace,
                                     const std::string& parentPath)
    : package_(package), baseNamespace_(baseNamespace), parentPath_(parentPath) {}

std::string AdapterFactoryEmitter::emitHeader() const {
    IndentedWriter w;
    auto ns = nsPath(package_, baseNamespace_, parentPath_);
    w.line("// <auto-generated/>");
    w.line("#pragma once");
    w.line("#include \"emf/common/ENotifier.h\"");
    w.line();
    w.line("namespace " + ns + " {");
    w.line();
    w.line("// 默认 Adapter 实现（占位）");
    w.line("class " + capitalizeFirst(package_->getName()) + "Adapter : public emf::common::EAdapter {");
    w.line("public:");
    {
        IndentScope s(w);
        w.line("void notifyChanged(const emf::common::Notification& notification) override { (void)notification; }");
        w.line("bool isAdapterForType(emf::common::Notifier* other) override { return other == target_; }");
    }
    w.line("};");
    w.line();
    w.line("class " + className() + " {");
    w.line("public:");
    {
        IndentScope s(w);
        w.line(className() + "() = default;");
        w.line("virtual ~" + className() + "() = default;");
        w.line();
        w.line("emf::common::EAdapter* createAdapter(emf::common::Notifier* target) {");
        {
            IndentScope s2(w);
            w.line("auto* a = new " + capitalizeFirst(package_->getName()) + "Adapter();");
            w.line("a->setTarget(target);");
            w.line("return a;");
        }
        w.line("}");
        w.line();
        w.line("static " + className() + "* instance();");
        w.line("static " + className() + "* eINSTANCE;");
        w.line("static void initialize();");
    }
    w.line("};");
    w.line();
    w.line("}  // namespace " + ns);
    return w.str();
}

std::string AdapterFactoryEmitter::emitSource() const {
    IndentedWriter w;
    auto ns = nsPath(package_, baseNamespace_, parentPath_);
    w.line("// <auto-generated/>");
    w.line("#include \"" + className() + ".h\"");
    w.line();
    w.line("namespace " + ns + " {");
    w.line();
    w.line(className() + "* " + className() + "::eINSTANCE = nullptr;");
    w.line();
    w.line(className() + "* " + className() + "::instance() { initialize(); return eINSTANCE; }");
    w.line();
    w.line("void " + className() + "::initialize() { if (eINSTANCE) return; eINSTANCE = new " + className() + "(); }");
    w.line();
    w.line("}  // namespace " + ns);
    return w.str();
}

}  // namespace emf::ecore::codegen
