// FactoryEmitter.cpp —— 生成 <Pkg>Factory.h/.cpp
// 对齐 Java: <Pkg>Factory.java / <Pkg>FactoryImpl.java
//
// 设计：生成的 Factory 继承 emf::ecore::EFactoryImpl（对齐 Java FactoryImpl extends EFactoryImpl）
//   - setEPackage 继承自 EFactoryImpl，接受 EPackage*（LibraryPackage IS-A EPackage）
//   - create<X>() 直接返回 new <X>()（单类单继承方案，无 Impl 后缀）
#include "emf/ecore/codegen/FactoryEmitter.h"
#include "emf/ecore/codegen/StringUtils.h"
#include "emf/ecore/EcoreImpls.h"
#include <string>
#include <vector>

namespace emf::ecore::codegen {

namespace {
std::string nsPath(emf::ecore::EPackage* p, const std::string& base, const std::string& parentPath) {
    std::string fullName = parentPath.empty() ? p->getName()
                                              : (parentPath + "/" + p->getName());
    std::string r;
    r.reserve(fullName.size() * 2);
    for (char c : fullName) {
        if (c == '/') r += "::";
        else r += c;
    }
    if (base.empty()) return r;
    return base + "::" + r;
}
std::vector<emf::ecore::EClass*> collectClasses(emf::ecore::EPackage* p) {
    std::vector<emf::ecore::EClass*> out;
    for (auto* c : p->getEClassifiers()) {
        if (auto* cls = dynamic_cast<emf::ecore::EClass*>(c)) out.push_back(cls);
    }
    return out;
}
std::string pkgClassName(emf::ecore::EPackage* p) {
    return capitalizeFirst(p->getName()) + "Package";
}
}  // namespace

FactoryEmitter::FactoryEmitter(emf::ecore::EPackage* package, const std::string& baseNamespace,
                               const std::string& parentPath)
    : package_(package), baseNamespace_(baseNamespace), parentPath_(parentPath) {}

std::string FactoryEmitter::emitHeader() const {
    IndentedWriter w;
    auto ns = nsPath(package_, baseNamespace_, parentPath_);
    w.line("// <auto-generated/>");
    w.line("#pragma once");
    w.line("#include \"emf/ecore/EcoreImpls.h\"");
    w.line("#include \"emf/common/EObject.h\"");
    w.line();
    w.line("namespace " + ns + " {");
    w.line();
    w.line("// 前向声明");
    for (auto* c : collectClasses(package_)) {
        w.line("class " + c->getName() + ";");
    }
    w.line("class " + pkgClassName(package_) + ";");
    w.line();
    w.line("// <Pkg>Factory: 工厂（对齐 Java <Pkg>FactoryImpl extends EFactoryImpl）");
    w.line("class " + className() + " : public emf::ecore::EFactoryImpl {");
    w.line("public:");
    {
        IndentScope s(w);
        w.line(className() + "() = default;");
        w.line();
        // create<X>() 方法
        for (auto* c : collectClasses(package_)) {
            w.line("virtual " + c->getName() + "* create" + c->getName() + "();");
        }
        w.line();
        // create(EClass*) 分派（对齐 Java EFactoryImpl.create(EClass) switch）
        // 必须覆盖，否则 EFactoryImpl::create 回退到 DynamicEObject，
        // 导致 Loader 创建的对象 vtable 是 DynamicEObject 而非生成的 C++ 类，
        // eGet/eIsSet 走反射路径返回错误结果。
        w.line("emf::common::EObject* create(const emf::ecore::EClass* eClass) const override;");
        w.line();
        w.line("static " + className() + "* instance();");
        w.line("static " + className() + "* eINSTANCE;");
        w.line("static void initialize();");
    }
    w.line("};");
    w.line();
    w.line("}  // namespace " + ns);
    return w.str();
}

std::string FactoryEmitter::emitSource() const {
    IndentedWriter w;
    auto ns = nsPath(package_, baseNamespace_, parentPath_);
    w.line("// <auto-generated/>");
    w.line("#include \"" + className() + ".h\"");
    w.line("#include \"" + pkgClassName(package_) + ".h\"");
    // 各 Class 头：create<X>() 调用 new <X>() 需要 complete type
    for (auto* c : collectClasses(package_)) {
        w.line("#include \"" + c->getName() + ".h\"");
    }
    w.line("#include \"emf/ecore/EcorePackage.h\"");
    w.line("#include \"emf/common/EPackageRegistry.h\"");
    w.line();
    w.line("namespace " + ns + " {");
    w.line();
    w.line(className() + "* " + className() + "::eINSTANCE = nullptr;");
    w.line();
    w.line(className() + "* " + className() + "::instance() { initialize(); return eINSTANCE; }");
    w.line();
    w.line("void " + className() + "::initialize() {");
    {
        IndentScope s(w);
        w.line("if (eINSTANCE) return;");
        w.line(pkgClassName(package_) + "::initialize();");
        w.line("if (eINSTANCE) return;  // Package::initialize() may have created us");
        w.line("eINSTANCE = new " + className() + "();");
        w.line("eINSTANCE->setEPackage(" + pkgClassName(package_) + "::eINSTANCE);");
    }
    w.line("}");
    w.line();
    // create<X>() 实现：单类单继承方案，直接 new <X>()
    for (auto* c : collectClasses(package_)) {
        w.line(c->getName() + "* " + className() + "::create" + c->getName() + "() {");
        {
            IndentScope s(w);
            w.line("return new " + c->getName() + "();");
        }
        w.line("}");
        w.line();
    }
    // create(EClass*) 分派：按 EClass 指针匹配本包的 EClass，命中则调用 create<X>()
    // 对齐 Java EFactoryImpl.create(EClass eClass) 的 switch(eClass.getClassifierID())
    // 未命中则委托父类 EFactoryImpl::create（最终回退到 DynamicEObject）
    // 注意：create(EClass*) 是 const（对齐 EFactoryImpl 基类签名），而 create<X>() 非 const，
    // 故用 const_cast 调用（create<X>() 只是 new 一个对象，const 安全）。
    w.line("emf::common::EObject* " + className() + "::create(const emf::ecore::EClass* eClass) const {");
    {
        IndentScope s(w);
        w.line("if (!eClass) return nullptr;");
        auto classes = collectClasses(package_);
        if (!classes.empty()) {
            w.line("auto* __pkg = " + pkgClassName(package_) + "::eINSTANCE;");
            w.line("auto* __self = const_cast<" + className() + "*>(this);");
            for (auto* c : classes) {
                std::string getter = "get" + c->getName() + "()";
                w.line("if (eClass == __pkg->" + getter + ") return __self->create" + c->getName() + "();");
            }
        }
        w.line("return emf::ecore::EFactoryImpl::create(eClass);");
    }
    w.line("}");
    w.line();
    w.line("}  // namespace " + ns);
    return w.str();
}

}  // namespace emf::ecore::codegen
