// SwitchEmitter.cpp —— 生成 <Pkg>Switch.h/.cpp
// 对齐 Java: <Pkg>Switch.java（org.eclipse.emf.ecore.util.Switch<T> 子类）
#include "emf/ecore/codegen/SwitchEmitter.h"
#include "emf/ecore/EcorePackage.h"
#include "emf/ecore/EcoreImpls.h"
#include <string>
#include <vector>

namespace emf::ecore::codegen {

namespace {
std::string nsPath(emf::ecore::EPackage* p, const std::string& base, const std::string& parentPath) {
    std::string fullName = parentPath.empty() ? p->getName()
                                              : (parentPath + "/" + p->getName());
    std::string r;
    r.reserve(fullName.size() * 2);
    for (char c : fullName) {
        if (c == '/') r += "::";
        else r += c;
    }
    if (base.empty()) return r;
    return base + "::" + r;
}
std::vector<emf::ecore::EClass*> collectClasses(emf::ecore::EPackage* p) {
    std::vector<emf::ecore::EClass*> out;
    for (auto* c : p->getEClassifiers()) {
        if (auto* cls = dynamic_cast<emf::ecore::EClass*>(c)) out.push_back(cls);
    }
    return out;
}
}  // namespace

SwitchEmitter::SwitchEmitter(emf::ecore::EPackage* package, const std::string& baseNamespace,
                             const std::string& parentPath)
    : package_(package), baseNamespace_(baseNamespace), parentPath_(parentPath) {}

std::string SwitchEmitter::emitHeader() const {
    IndentedWriter w;
    auto ns = nsPath(package_, baseNamespace_, parentPath_);
    w.line("// <auto-generated/>");
    w.line("#pragma once");
    w.line("#include \"emf/common/EObject.h\"");
    w.line("#include \"emf/common/EList.h\"");
    w.line();
    w.line("namespace " + ns + " {");
    w.line();
    w.line("// <Pkg>Switch: 类型分发（对齐 Java <Pkg>Switch<T> extends Switch<T>）");
    w.line("template <typename T>");
    w.line("class " + className() + " {");
    w.line("public:");
    {
        IndentScope s(w);
        w.line(className() + "() = default;");
        w.line("virtual ~" + className() + "() = default;");
        w.line();
        w.line("T doSwitch(emf::common::EObject* obj) {");
        {
            IndentScope s2(w);
            w.line("if (!obj) return defaultCase(nullptr);");
            w.line("int id = obj->eClass() ? obj->eClass()->getFeatureCount() : -1;");
            w.line("(void)id;");
            w.line("// 按 EClass 名字 dispatch（单类单继承方案：直接用类名，无 Impl 后缀）");
            for (auto* c : collectClasses(package_)) {
                w.line("{ auto* t = dynamic_cast<" + c->getName() + "*>(obj); if (t) return case" + c->getName() + "(t); }");
            }
            w.line("return defaultCase(obj);");
        }
        w.line("}");
        w.line();
        for (auto* c : collectClasses(package_)) {
            w.line("virtual T case" + c->getName() + "(" + c->getName() + "* object) { return defaultCase(object); }");
        }
        w.line("virtual T defaultCase(emf::common::EObject* object) { (void)object; return T{}; }");
    }
    w.line("};");
    w.line();
    w.line("}  // namespace " + ns);
    return w.str();
}

std::string SwitchEmitter::emitSource() const {
    // 模板实现都在头文件
    return "// Switch is template; implementation lives in " + className() + ".h\n";
}

}  // namespace emf::ecore::codegen
