// ValidatorEmitter.cpp —— 生成 <Pkg>Validator.h/.cpp
// 对齐 Java: <Pkg>Validator.java (EObjectValidator 子类)
#include "emf/ecore/codegen/ValidatorEmitter.h"
#include "emf/ecore/codegen/StringUtils.h"
#include "emf/ecore/EcorePackage.h"
#include "emf/common/Diagnostic.h"
#include <string>
#include <vector>

namespace emf::ecore::codegen {

namespace {
std::string nsPath(emf::ecore::EPackage* p, const std::string& base, const std::string& parentPath) {
    std::string fullName = parentPath.empty() ? p->getName()
                                              : (parentPath + "/" + p->getName());
    std::string r;
    r.reserve(fullName.size() * 2);
    for (char c : fullName) {
        if (c == '/') r += "::";
        else r += c;
    }
    if (base.empty()) return r;
    return base + "::" + r;
}
std::vector<emf::ecore::EClass*> collectClasses(emf::ecore::EPackage* p) {
    std::vector<emf::ecore::EClass*> out;
    for (auto* c : p->getEClassifiers()) {
        if (auto* cls = dynamic_cast<emf::ecore::EClass*>(c)) out.push_back(cls);
    }
    return out;
}
std::string pkgClassName(emf::ecore::EPackage* p, const std::string& suffix) {
    return capitalizeFirst(p->getName()) + suffix;
}
}  // namespace

ValidatorEmitter::ValidatorEmitter(emf::ecore::EPackage* package, const std::string& baseNamespace,
                                  const std::string& parentPath)
    : package_(package), baseNamespace_(baseNamespace), parentPath_(parentPath) {}

std::string ValidatorEmitter::emitHeader() const {
    IndentedWriter w;
    auto ns = nsPath(package_, baseNamespace_, parentPath_);
    w.line("// <auto-generated/>");
    w.line("#pragma once");
    w.line("#include \"emf/common/Diagnostic.h\"");
    w.line("#include \"emf/common/EObject.h\"");
    w.line("#include \"emf/ecore/util/EObjectValidator.h\"");
    w.line("#include \"emf/ecore/util/EValidatorRegistryImpl.h\"");
    w.line();
    w.line("namespace " + ns + " {");
    w.line();
    w.line("// <Pkg>Validator: 校验本 EPackage 内的 EObject");
    w.line("// 对齐 Java <Pkg>Validator (extends EObjectValidator, implements EValidator)");
    w.line("// 继承 EObjectValidator 获得内置约束；实现 emf::ecore::util::EValidator 接口以便自我注册到 Registry");
    w.line("class " + className() + " : public emf::ecore::util::EObjectValidator,");
    {
        IndentScope s(w);
        w.line("public emf::ecore::util::EValidator {");
    }
    w.line("public:");
    {
        IndentScope s(w);
        w.line(className() + "() = default;");
        w.line();
        w.line("// 旧 API：返回 Diagnostic 列表");
        w.line("std::vector<emf::common::Diagnostic> validate(emf::common::EObject* object);");
        w.line();
        w.line("// EValidator 接口：写入 DiagnosticChain，返回是否通过");
        w.line("// V4 修复：先调基类 validate_EveryDefaultConstraint 做基础约束，");
        w.line("// 再调 validateInvariants 做 per-EClass invariant（从 OCL/Constraints annotation 加载）。");
        w.line("bool validate(emf::common::EObject* object, emf::common::DiagnosticChain* chain,");
        w.line("              emf::ecore::util::ValidationContext* context = nullptr) override;");
        w.line();
        w.line("// per-EClass invariant 校验：遍历 object.eClass() 的 OCL/Constraints annotation，");
        w.line("// 用 AnnotationConstraintLoader 加载并求值。对齐 Java codegen 的 validateEClass_<Name>。");
        w.line("bool validateInvariants(emf::common::EObject* object, emf::common::DiagnosticChain* chain);");
        w.line();
        w.line("static " + className() + "* instance();");
        w.line("static " + className() + "* eINSTANCE;");
        w.line("static void initialize();");
    }
    w.line("};");
    w.line();
    w.line("}  // namespace " + ns);
    return w.str();
}

std::string ValidatorEmitter::emitSource() const {
    IndentedWriter w;
    auto ns = nsPath(package_, baseNamespace_, parentPath_);
    w.line("// <auto-generated/>");
    w.line("#include \"" + className() + ".h\"");
    w.line("#include \"" + pkgClassName(package_, "Package") + ".h\"");
    w.line("#include \"emf/ecore/EcorePackage.h\"");
    w.line("#include \"emf/common/EObject.h\"");
    w.line("#include \"emf/validation/AnnotationConstraintLoader.h\"");
    w.line("#include \"emf/validation/EValidator.h\"");
    w.line("#include <any>");
    w.line("#include <unordered_map>");
    w.line();
    w.line("namespace " + ns + " {");
    w.line();
    w.line(className() + "* " + className() + "::eINSTANCE = nullptr;");
    w.line();
    w.line(className() + "* " + className() + "::instance() { initialize(); return eINSTANCE; }");
    w.line();
    w.line("void " + className() + "::initialize() {");
    {
        IndentScope s(w);
        w.line("if (eINSTANCE) return;");
        w.line(pkgClassName(package_, "Package") + "::initialize();");
        w.line("eINSTANCE = new " + className() + "();");
        w.line("// 自我注册到 ecore 层 EValidator.Registry（对齐 Java EValidator.Registry.INSTANCE）");
        w.line("// 说明：emf-ecore 不能反向依赖 emf-validation，故注册到 emf::ecore::util 层 Registry；");
        w.line("//       emf-validation 的 Diagnostician 以此 Registry 为 fallback 分派（见 Diagnostician）。");
        w.line("emf::ecore::util::EValidatorRegistryImpl::instance().put(");
        {
            IndentScope s2(w);
            w.line(pkgClassName(package_, "Package") + "::eINSTANCE, eINSTANCE);");
        }
    }
    w.line("}");
    w.line();
    w.line("bool " + className() + "::validate(emf::common::EObject* object,");
    {
        IndentScope s(w);
        w.line("emf::common::DiagnosticChain* chain,");
        w.line("emf::ecore::util::ValidationContext* context) {");
    }
    {
        IndentScope s(w);
        w.line("if (!object || !chain) return true;");
        w.line("std::unordered_map<std::string, std::any> ctx;");
        w.line("if (!context) context = &ctx;");
        w.line("// V4 修复：先基类默认约束，再 per-EClass invariant");
        w.line("bool ok = emf::ecore::util::EObjectValidator::validate_EveryDefaultConstraint(object, chain, context);");
        w.line("if (!validateInvariants(object, chain)) ok = false;");
        w.line("return ok;");
    }
    w.line("}");
    w.line();
    w.line("bool " + className() + "::validateInvariants(emf::common::EObject* object,");
    {
        IndentScope s(w);
        w.line("emf::common::DiagnosticChain* chain) {");
    }
    {
        IndentScope s(w);
        w.line("if (!object || !object->eClass()) return true;");
        w.line("// V4：从 eClass 的 OCL/Constraints annotation 加载 invariant 并求值");
        w.line("// 用临时 emf::validation::EValidator 收集约束，逐个求值，失败追加 Diagnostic 到 chain");
        w.line("emf::validation::EValidator tmpValidator;");
        w.line("int n = emf::validation::AnnotationConstraintLoader::loadAll(tmpValidator, object->eClass());");
        w.line("if (n == 0) return true;");
        w.line("auto diags = tmpValidator.validate(object);");
        w.line("bool ok = true;");
        w.line("for (auto& d : diags) {");
        {
            IndentScope s2(w);
            w.line("chain->add(std::make_shared<emf::common::Diagnostic>(d.severity(), d.source(), d.code(), d.message()));");
            w.line("if (d.severity() == emf::common::Diagnostic::Severity::ERROR ||");
            w.line("    d.severity() == emf::common::Diagnostic::Severity::CANCEL) ok = false;");
        }
        w.line("}");
        w.line("return ok;");
    }
    w.line("}");
    w.line();
    w.line("std::vector<emf::common::Diagnostic> " + className() + "::validate(emf::common::EObject* object) {");
    {
        IndentScope s(w);
        w.line("std::vector<emf::common::Diagnostic> r;");
        w.line("if (!object) return r;");
        // Diagnostic ctor (与 emf::common::Diagnostic 一致): Diagnostic(Severity, source, code, message, data)
        w.line("if (!object->eClass()) { r.emplace_back(emf::common::Diagnostic::Severity::ERROR, std::string(\"validator\"), 0, std::string(\"eClass is null\"), std::vector<std::shared_ptr<emf::common::Diagnostic>>{}); return r; }");
        w.line("auto* cls = object->eClass();");
        w.line("auto* pkg = cls->getEPackage();");
        w.line("if (pkg && pkg->getName() == " + pkgClassName(package_, "Package") + "::eNAME) {");
        {
            IndentScope s2(w);
            w.line("// 类型属于本 EPackage：委托基类 EObjectValidator.validate_EveryDefaultConstraint 做基础校验");
            w.line("emf::common::DiagnosticChain chain;");
            w.line("std::unordered_map<std::string, std::any> ctx;");
            w.line("emf::ecore::util::EObjectValidator::validate_EveryDefaultConstraint(object, &chain, &ctx);");
            w.line("for (auto& d : chain.get()) {");
            {
                IndentScope s3(w);
                w.line("if (d && d->severity() != emf::common::Diagnostic::Severity::OK) {");
                {
                    IndentScope s4(w);
                    w.line("r.emplace_back(d->severity(), d->source(), d->code(), d->message());");
                }
                w.line("}");
            }
            w.line("}");
        }
        w.line("} else {");
        {
            IndentScope s2(w);
            w.line("r.emplace_back(emf::common::Diagnostic::Severity::ERROR, std::string(\"validator\"), 0, std::string(\"object is not of \") + " + pkgClassName(package_, "Package") + "::eNAME, std::vector<std::shared_ptr<emf::common::Diagnostic>>{});");
        }
        w.line("}");
        w.line("return r;");
    }
    w.line("}");
    w.line();
    w.line("}  // namespace " + ns);
    return w.str();
}

}  // namespace emf::ecore::codegen
